### ISSUE TITLE
說明「龍/童/辛/音」vs「立」並不是「強行區分」，是多年以來的約定俗成

### ISSUE THREAD

**Issue by aikahiiragi** [Des-Magmeta/Magmeta-characters#1]
您好！首先如果讓閣下覺得離題的話非常抱歉，因爲找了一整天都找不到個人訊息功能，所以只能在看起來好像比較相關的項目上跟你說。

我想說的是，「龍/童/辛/音」vs「立」的分別，不但一點兒都不是「強行區分」，而且是約定俗成的。至少在我自小至大的親眼的目擊之中，對我們來說，這種區分從小就習慣。從我還未出世，父母輩甚至祖父母輩時，日常交通標示的大字就已經會這樣區分。這已是生活的一部份。附圖都是一些例子。

希望你明白我的發言沒有任何強迫的意思。我指出這區分並非強行，但同時並沒有強迫他們要區分，沒有說其他人「只要不區分就任何情況都不行」。但我支持、選擇或提意區分時，不但是我的自由，也只是反映了我自小長大的地方、環境中平時的習慣。這種區分是我們一向以來的約定俗成。

我也體諒不同人有不同的生活環境，以閣下的資料看似乎生活在內地，沒有親身經歷過使用傳承字形的環境，所以不了解。不過我認爲如果是不了解的話，應該平心靜氣好好了解，不應該在不了解的情況下就想像成一定是「強行區分」，把這種違背事實的想像用陳敘事實般的肯定語氣說出來。

希望能令你了解。非常抱歉，也非常感謝！

![image](https://github.com/user-attachments/assets/ff8e945e-85b6-46f5-94fe-9c59e72fd385)
![image](https://github.com/user-attachments/assets/6f79717d-6839-42c0-8edc-9061bbd1fa30)
![image](https://github.com/user-attachments/assets/c585684a-e5bb-4033-9c7d-8302c12bc3f1)
![image](https://github.com/user-attachments/assets/2e807af3-b7c2-410c-9042-d981aaaf76da)

**Comment by Des-Magmeta** [comment]
@aikahiiragi 抱歉本人才疏學淺，經查閱資料，實際上「龍/童/辛/音」等字上半部分在早期鉛字中常常依小篆設計成「二」形。這一點當然符合字理。而本人也看到在[「源樣明體 丹 / GenYoMin2TC」](https://github.com/ButTaiwan/genyo-font)、[「秋空黑體 CL」](https://github.com/ChiuMing-Neko/ChiuKongGothic) 、[「霞鶩緻宋 CL」](https://github.com/lxgw/LxgwZhiSong) 等遵循傳統字形的字型中，這些字的上半部分製作成「亠」形而非「二」形，早期 Windows 中的細明體亦如此。但是我們並不能因此認為這不符合傳統字形的設計原則。

附 Windows 98 版本的「細明體」字圖：
![Screenshot_20241019_133636](https://github.com/user-attachments/assets/aa1b262f-9025-466a-b980-3587b3cd764c)

因為本人接觸傳承字形的頻率較低，本人接觸的傳統印刷體中更多的是將這些字設計做「亠」的部分，這也導致這一不負責任的結論的產生。非常抱歉令你造成誤解。後續關於傳承字形之爭論，本人將儘量避開不熟悉的部分，或經查閱資料後再談論。希望能讓你瞭解。如有問題，還請多多指正。

**Comment by aikahiiragi** [comment]
謝謝你的理解。 我也知道因爲「舊字形」或傳承字形是比較寬廣，所以當中有些注重字理，有些則以其他方式取捨。我個人也不反對以其他方式取捨的舊字形存在，不過希望就算有它們的存在，同時也能讓注重字理的用戶感到滿足，不希望說「只要有了寬泛式的印刷體就成，不必滿足需求重視字理方面的用戶」。

尤其是以這個「二」形來說，過去有人多番鬧事，強迫《傳承字形部件檢校表》必須接受「亠」形，又有人借這一點在QQ群中傷《傳承字形部件檢校表》，但明明這部件是我出生成長就常常慣看的部件。

當然每一套字型的製作或改作計劃，還是以項目主人的決定為依歸，我也只是建議，然後碰上之前的爭論。希望閣下體諒我的魯莽，有什麼失禮的地方都希望還請多多原諒，感謝！
